==16458== Memcheck, a memory error detector
==16458== Copyright (C) 2002-2009, and GNU GPL'd, by Julian Seward et al.
==16458== Using Valgrind-3.5.0-Debian and LibVEX; rerun with -h for copyright info
==16458== Command: ./try.py
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BDB: code_dealloc (codeobject.c:260)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x423c010 is 8 bytes before a block of size 288 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x8081E6C: PyList_Append (listobject.c:62)
==16458==    by 0x80FE916: r_object (marshal.c:731)
==16458==    by 0x80FE0DB: r_object (marshal.c:794)
==16458==    by 0x80FE56A: r_object (marshal.c:930)
==16458==    by 0x81004D1: PyMarshal_ReadLastObjectFromFile (marshal.c:1107)
==16458==    by 0x80FB3B1: load_source_module (import.c:769)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80A5F43: tupledealloc (tupleobject.c:170)
==16458==    by 0x8131C8B: code_dealloc (codeobject.c:261)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==  Address 0x423d010 is 8 bytes inside a block of size 100 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x8081E6C: PyList_Append (listobject.c:62)
==16458==    by 0x80FE916: r_object (marshal.c:731)
==16458==    by 0x80FE0DB: r_object (marshal.c:794)
==16458==    by 0x80FE56A: r_object (marshal.c:930)
==16458==    by 0x81004D1: PyMarshal_ReadLastObjectFromFile (marshal.c:1107)
==16458==    by 0x80FB3B1: load_source_module (import.c:769)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x80A5F59: tupledealloc (tupleobject.c:183)
==16458==    by 0x8131C73: code_dealloc (codeobject.c:262)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==  Address 0x423c010 is 8 bytes before a block of size 288 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x8081E6C: PyList_Append (listobject.c:62)
==16458==    by 0x80FE916: r_object (marshal.c:731)
==16458==    by 0x80FE0DB: r_object (marshal.c:794)
==16458==    by 0x80FE56A: r_object (marshal.c:930)
==16458==    by 0x81004D1: PyMarshal_ReadLastObjectFromFile (marshal.c:1107)
==16458==    by 0x80FB3B1: load_source_module (import.c:769)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x423d010 is 8 bytes inside a block of size 100 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x8081E6C: PyList_Append (listobject.c:62)
==16458==    by 0x80FE916: r_object (marshal.c:731)
==16458==    by 0x80FE0DB: r_object (marshal.c:794)
==16458==    by 0x80FE56A: r_object (marshal.c:930)
==16458==    by 0x81004D1: PyMarshal_ReadLastObjectFromFile (marshal.c:1107)
==16458==    by 0x80FB3B1: load_source_module (import.c:769)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x80946D8: PyObject_Free (obmalloc.c:931)
==16458==    by 0x812725E: PyGrammar_AddAccelerators (acceler.c:124)
==16458==    by 0x812804F: PyParser_New (parser.c:77)
==16458==    by 0x805CAF6: parsetok (parsetok.c:136)
==16458==    by 0x8104242: PyParser_ASTFromString (pythonrun.c:1474)
==16458==    by 0x81064A4: PyRun_StringFlags (pythonrun.c:1334)
==16458==    by 0x80E5FFC: run_script (prickelpit.c:249)
==16458==    by 0x80E7A97: init_prickelpit (prickelpit.c:2158)
==16458==    by 0x80E360A: _PyStackless_Init (stacklessmodule.c:1170)
==16458==    by 0x8106B86: Py_InitializeEx (pythonrun.c:256)
==16458==    by 0x8107311: Py_Initialize (pythonrun.c:372)
==16458==    by 0x805C18D: Py_Main (main.c:485)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x80946E9: PyObject_Free (obmalloc.c:931)
==16458==    by 0x812725E: PyGrammar_AddAccelerators (acceler.c:124)
==16458==    by 0x812804F: PyParser_New (parser.c:77)
==16458==    by 0x805CAF6: parsetok (parsetok.c:136)
==16458==    by 0x8104242: PyParser_ASTFromString (pythonrun.c:1474)
==16458==    by 0x81064A4: PyRun_StringFlags (pythonrun.c:1334)
==16458==    by 0x80E5FFC: run_script (prickelpit.c:249)
==16458==    by 0x80E7A97: init_prickelpit (prickelpit.c:2158)
==16458==    by 0x80E360A: _PyStackless_Init (stacklessmodule.c:1170)
==16458==    by 0x8106B86: Py_InitializeEx (pythonrun.c:256)
==16458==    by 0x8107311: Py_Initialize (pythonrun.c:372)
==16458==    by 0x805C18D: Py_Main (main.c:485)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x812725E: PyGrammar_AddAccelerators (acceler.c:124)
==16458==    by 0x812804F: PyParser_New (parser.c:77)
==16458==    by 0x805CAF6: parsetok (parsetok.c:136)
==16458==    by 0x8104242: PyParser_ASTFromString (pythonrun.c:1474)
==16458==    by 0x81064A4: PyRun_StringFlags (pythonrun.c:1334)
==16458==    by 0x80E5FFC: run_script (prickelpit.c:249)
==16458==    by 0x80E7A97: init_prickelpit (prickelpit.c:2158)
==16458==    by 0x80E360A: _PyStackless_Init (stacklessmodule.c:1170)
==16458==    by 0x8106B86: Py_InitializeEx (pythonrun.c:256)
==16458==    by 0x8107311: Py_Initialize (pythonrun.c:372)
==16458==    by 0x805C18D: Py_Main (main.c:485)
==16458==  Address 0x4242010 is 584 bytes inside a block of size 676 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x812725E: PyGrammar_AddAccelerators (acceler.c:124)
==16458==    by 0x812804F: PyParser_New (parser.c:77)
==16458==    by 0x805CAF6: parsetok (parsetok.c:136)
==16458==    by 0x8104242: PyParser_ASTFromString (pythonrun.c:1474)
==16458==    by 0x81064A4: PyRun_StringFlags (pythonrun.c:1334)
==16458==    by 0x80E5FFC: run_script (prickelpit.c:249)
==16458==    by 0x80E7A97: init_prickelpit (prickelpit.c:2158)
==16458==    by 0x80E360A: _PyStackless_Init (stacklessmodule.c:1170)
==16458==    by 0x8106B86: Py_InitializeEx (pythonrun.c:256)
==16458==    by 0x8107311: Py_Initialize (pythonrun.c:372)
==16458==    by 0x805C18D: Py_Main (main.c:485)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x810652B: PyRun_StringFlags (pythonrun.c:1381)
==16458==    by 0x80E5FFC: run_script (prickelpit.c:249)
==16458==    by 0x80E7A97: init_prickelpit (prickelpit.c:2158)
==16458==    by 0x80E360A: _PyStackless_Init (stacklessmodule.c:1170)
==16458==    by 0x8106B86: Py_InitializeEx (pythonrun.c:256)
==16458==    by 0x8107311: Py_Initialize (pythonrun.c:372)
==16458==    by 0x805C18D: Py_Main (main.c:485)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4298010 is not stack'd, malloc'd or (recently) free'd
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x8137998: gen_dealloc (genobject.c:41)
==16458==    by 0x80E7B2B: init_prickelpit (prickelpit.c:2171)
==16458==    by 0x80E360A: _PyStackless_Init (stacklessmodule.c:1170)
==16458==    by 0x8106B86: Py_InitializeEx (pythonrun.c:256)
==16458==    by 0x8107311: Py_Initialize (pythonrun.c:372)
==16458==    by 0x805C18D: Py_Main (main.c:485)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4298010 is not stack'd, malloc'd or (recently) free'd
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x80946D8: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80A5F43: tupledealloc (tupleobject.c:170)
==16458==    by 0x8131C8B: code_dealloc (codeobject.c:261)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x80946E9: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80A5F43: tupledealloc (tupleobject.c:170)
==16458==    by 0x8131C8B: code_dealloc (codeobject.c:261)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BDB: code_dealloc (codeobject.c:260)
==16458==    by 0x80A5F43: tupledealloc (tupleobject.c:170)
==16458==    by 0x8131C8B: code_dealloc (codeobject.c:261)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==  Address 0x4328010 is 344 bytes inside a block of size 352 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x40E0509: fclose@@GLIBC_2.1 (iofclose.c:88)
==16458==    by 0x80FB3D0: load_source_module (import.c:994)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x8138178: frame_dealloc (frameobject.c:472)
==16458==    by 0x80D9CCD: PyEval_EvalFrame_value (ceval.c:2978)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DF16B: slp_frame_dispatch (stacklesseval.c:692)
==16458==    by 0x80D84F6: PyEval_EvalCode (ceval.c:543)
==16458==    by 0x80F953E: PyImport_ExecCodeModuleEx (import.c:677)
==16458==  Address 0x4345010 is 16,752 bytes inside a block of size 18,016 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x805CD33: parsetok (parsetok.c:219)
==16458==    by 0x81041C1: PyParser_ASTFromString (pythonrun.c:1474)
==16458==    by 0x81064A4: PyRun_StringFlags (pythonrun.c:1334)
==16458==    by 0x80D6C12: builtin_eval (bltinmodule.c:691)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DF16B: slp_frame_dispatch (stacklesseval.c:692)
==16458==    by 0x80D84F6: PyEval_EvalCode (ceval.c:543)
==16458==    by 0x80F953E: PyImport_ExecCodeModuleEx (import.c:677)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x8138178: frame_dealloc (frameobject.c:472)
==16458==    by 0x810C743: tb_dealloc (traceback.c:28)
==16458==    by 0x810C753: tb_dealloc (traceback.c:27)
==16458==    by 0x808E770: PyDict_DelItem (dictobject.c:755)
==16458==    by 0x808E7DB: PyDict_DelItemString (dictobject.c:2314)
==16458==    by 0x80D9B58: PyEval_EvalFrame_value (ceval.c:3466)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DF16B: slp_frame_dispatch (stacklesseval.c:692)
==16458==  Address 0x434c010 is 17,352 bytes inside a block of size 18,016 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x805CD33: parsetok (parsetok.c:219)
==16458==    by 0x81041C1: PyParser_ASTFromString (pythonrun.c:1474)
==16458==    by 0x81064A4: PyRun_StringFlags (pythonrun.c:1334)
==16458==    by 0x80D6C12: builtin_eval (bltinmodule.c:691)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DF16B: slp_frame_dispatch (stacklesseval.c:692)
==16458==    by 0x80D84F6: PyEval_EvalCode (ceval.c:543)
==16458==    by 0x80F953E: PyImport_ExecCodeModuleEx (import.c:677)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x80A5F59: tupledealloc (tupleobject.c:183)
==16458==    by 0x8131C8B: code_dealloc (codeobject.c:261)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==  Address 0x42ee010 is 104 bytes inside a block of size 1,888 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x8131BDB: code_dealloc (codeobject.c:260)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BF3: code_dealloc (codeobject.c:268)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC630: ensure_fromlist (import.c:2502)
==16458==    by 0x80FCC35: import_module_level (import.c:2170)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x43b6010 is 528 bytes inside a block of size 1,416 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x8081E6C: PyList_Append (listobject.c:62)
==16458==    by 0x80FE916: r_object (marshal.c:731)
==16458==    by 0x80FE0DB: r_object (marshal.c:794)
==16458==    by 0x80FE559: r_object (marshal.c:927)
==16458==    by 0x81004D1: PyMarshal_ReadLastObjectFromFile (marshal.c:1107)
==16458==    by 0x80FB3B1: load_source_module (import.c:769)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC630: ensure_fromlist (import.c:2502)
==16458==    by 0x80FCC35: import_module_level (import.c:2170)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x8094BB2: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x812762C: PyNode_AddChild (node.c:98)
==16458==    by 0x8127CE0: PyParser_AddToken (parser.c:126)
==16458==    by 0x805CB7C: parsetok (parsetok.c:199)
==16458==    by 0x810407F: PyParser_ASTFromFile (pythonrun.c:1503)
==16458==    by 0x8105D17: PyRun_FileExFlags (pythonrun.c:1354)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x8094BBD: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x812762C: PyNode_AddChild (node.c:98)
==16458==    by 0x8127CE0: PyParser_AddToken (parser.c:126)
==16458==    by 0x805CB7C: parsetok (parsetok.c:199)
==16458==    by 0x810407F: PyParser_ASTFromFile (pythonrun.c:1503)
==16458==    by 0x8105D17: PyRun_FileExFlags (pythonrun.c:1354)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x8094BB2: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x812762C: PyNode_AddChild (node.c:98)
==16458==    by 0x8127ED6: PyParser_AddToken (parser.c:112)
==16458==    by 0x805CB7C: parsetok (parsetok.c:199)
==16458==    by 0x810407F: PyParser_ASTFromFile (pythonrun.c:1503)
==16458==    by 0x8105D17: PyRun_FileExFlags (pythonrun.c:1354)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x8094BBD: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x812762C: PyNode_AddChild (node.c:98)
==16458==    by 0x8127ED6: PyParser_AddToken (parser.c:112)
==16458==    by 0x805CB7C: parsetok (parsetok.c:199)
==16458==    by 0x810407F: PyParser_ASTFromFile (pythonrun.c:1503)
==16458==    by 0x8105D17: PyRun_FileExFlags (pythonrun.c:1354)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x81279FD: freechildren (node.c:135)
==16458==    by 0x8127A34: PyNode_Free (node.c:123)
==16458==    by 0x81040BA: PyParser_ASTFromFile (pythonrun.c:1512)
==16458==    by 0x8105D17: PyRun_FileExFlags (pythonrun.c:1354)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4405010 is 260,544 bytes inside a block of size 262,144 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x8094839: PyObject_Free (obmalloc.c:1019)
==16458==    by 0x8127925: freechildren (node.c:135)
==16458==    by 0x8127834: freechildren (node.c:133)
==16458==    by 0x8127834: freechildren (node.c:133)
==16458==    by 0x8127834: freechildren (node.c:133)
==16458==    by 0x8127834: freechildren (node.c:133)
==16458==    by 0x8127A34: PyNode_Free (node.c:123)
==16458==    by 0x81040BA: PyParser_ASTFromFile (pythonrun.c:1512)
==16458==    by 0x8105D17: PyRun_FileExFlags (pythonrun.c:1354)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x80E9C8D: compiler_next_instr (compile.c:639)
==16458==    by 0x80E9DB1: compiler_addop_j (compile.c:1044)
==16458==    by 0x80F11CF: compiler_if (compile.c:1602)
==16458==    by 0x80F1CB1: compiler_mod (compile.c:1187)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4406010 is 0 bytes after a block of size 40 alloc'd
==16458==    at 0x4024C1C: malloc (vg_replace_malloc.c:195)
==16458==    by 0x8109E97: PySymtable_Build (symtable.c:195)
==16458==    by 0x80F1DBD: PyAST_Compile (compile.c:278)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x80E9C8D: compiler_next_instr (compile.c:639)
==16458==    by 0x80E9D21: compiler_addop_i (compile.c:1026)
==16458==    by 0x80ED6FA: compiler_visit_expr (compile.c:2797)
==16458==    by 0x80EF1CC: compiler_visit_stmt (compile.c:2186)
==16458==    by 0x80F1CB1: compiler_mod (compile.c:1187)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4406010 is 0 bytes after a block of size 40 alloc'd
==16458==    at 0x4024C1C: malloc (vg_replace_malloc.c:195)
==16458==    by 0x8109E97: PySymtable_Build (symtable.c:195)
==16458==    by 0x80F1DBD: PyAST_Compile (compile.c:278)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x80EBB62: assemble (compile.c:3689)
==16458==    by 0x80F1BBD: compiler_mod (compile.c:1231)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4407010 is 128 bytes inside a block of size 512 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x80E9C8D: compiler_next_instr (compile.c:639)
==16458==    by 0x80E9D21: compiler_addop_i (compile.c:1026)
==16458==    by 0x80ED6FA: compiler_visit_expr (compile.c:2797)
==16458==    by 0x80EF1CC: compiler_visit_stmt (compile.c:2186)
==16458==    by 0x80F1CB1: compiler_mod (compile.c:1187)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x80EBBF8: assemble (compile.c:3987)
==16458==    by 0x80F1BBD: compiler_mod (compile.c:1231)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4407010 is 128 bytes inside a block of size 512 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x80E9C8D: compiler_next_instr (compile.c:639)
==16458==    by 0x80E9D21: compiler_addop_i (compile.c:1026)
==16458==    by 0x80ED6FA: compiler_visit_expr (compile.c:2797)
==16458==    by 0x80EF1CC: compiler_visit_stmt (compile.c:2186)
==16458==    by 0x80F1CB1: compiler_mod (compile.c:1187)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x80EC100: assemble (compile.c:3499)
==16458==    by 0x80F1BBD: compiler_mod (compile.c:1231)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4407010 is 128 bytes inside a block of size 512 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x80E9C8D: compiler_next_instr (compile.c:639)
==16458==    by 0x80E9D21: compiler_addop_i (compile.c:1026)
==16458==    by 0x80ED6FA: compiler_visit_expr (compile.c:2797)
==16458==    by 0x80EF1CC: compiler_visit_stmt (compile.c:2186)
==16458==    by 0x80F1CB1: compiler_mod (compile.c:1187)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x80E960E: compiler_unit_free (compile.c:423)
==16458==    by 0x80F1BCB: compiler_mod (compile.c:521)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x4407010 is 128 bytes inside a block of size 512 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x80E9C8D: compiler_next_instr (compile.c:639)
==16458==    by 0x80E9D21: compiler_addop_i (compile.c:1026)
==16458==    by 0x80ED6FA: compiler_visit_expr (compile.c:2797)
==16458==    by 0x80EF1CC: compiler_visit_stmt (compile.c:2186)
==16458==    by 0x80F1CB1: compiler_mod (compile.c:1187)
==16458==    by 0x80F1DD9: PyAST_Compile (compile.c:288)
==16458==    by 0x8105D47: PyRun_FileExFlags (pythonrun.c:1375)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FBA88: load_package (import.c:1073)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==  Address 0x4409010 is 312 bytes inside a block of size 352 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x40E0E6F: __fopen_internal (iofopen.c:98)
==16458==    by 0x40E342B: fopen64 (iofopen64.c:39)
==16458==    by 0x80FA313: find_module (import.c:1476)
==16458==    by 0x80FC258: import_submodule (import.c:2581)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x80DF55B: slp_eval_frame_newstack (stacklesseval.c:450)
==16458==    by 0x80DECBF: PyEval_EvalFrameEx_slp (ceval.c:782)
==16458==    by 0x80DF16B: slp_frame_dispatch (stacklesseval.c:692)
==16458==    by 0x80D84F6: PyEval_EvalCode (ceval.c:543)
==16458==    by 0x80F953E: PyImport_ExecCodeModuleEx (import.c:677)
==16458==    by 0x80FB2B3: load_source_module (import.c:1017)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==  Address 0x4470010 is 8 bytes before a block of size 1,206 alloc'd
==16458==    at 0x4024C1C: malloc (vg_replace_malloc.c:195)
==16458==    by 0x809BD4B: PyString_FromStringAndSize (stringobject.c:83)
==16458==    by 0x80FE450: r_object (marshal.c:717)
==16458==    by 0x80FE544: r_object (marshal.c:924)
==16458==    by 0x80FE0DB: r_object (marshal.c:794)
==16458==    by 0x80FE559: r_object (marshal.c:927)
==16458==    by 0x81004D1: PyMarshal_ReadLastObjectFromFile (marshal.c:1107)
==16458==    by 0x80FB3B1: load_source_module (import.c:769)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x80946D8: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BDB: code_dealloc (codeobject.c:260)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x80946E9: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BDB: code_dealloc (codeobject.c:260)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC855: import_module_level (import.c:2133)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x80A3529: PyString_Format (stringobject.c:5064)
==16458==    by 0x80616FD: binary_op1 (abstract.c:918)
==16458==    by 0x806372F: PyNumber_Remainder (abstract.c:970)
==16458==    by 0x80DC022: PyEval_EvalFrame_value (ceval.c:1378)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DF16B: slp_frame_dispatch (stacklesseval.c:692)
==16458==    by 0x8139695: function_call (funcobject.c:535)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80685EF: instancemethod_call (classobject.c:2586)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==  Address 0x449b010 is not stack'd, malloc'd or (recently) free'd
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x8111938: _PyObject_GC_Resize (gcmodule.c:1404)
==16458==    by 0x81387F1: PyFrame_New (frameobject.c:679)
==16458==    by 0x80DDCD5: PyEval_EvalFrame_value (ceval.c:4143)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==  Address 0x4499010 is 8 bytes before a block of size 344 alloc'd
==16458==    at 0x4024C1C: malloc (vg_replace_malloc.c:195)
==16458==    by 0x8112A6B: _PyObject_GC_Malloc (gcmodule.c:1359)
==16458==    by 0x8112B49: _PyObject_GC_NewVar (gcmodule.c:1391)
==16458==    by 0x8138838: PyFrame_New (frameobject.c:666)
==16458==    by 0x80DDCD5: PyEval_EvalFrame_value (ceval.c:4143)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x80A5F59: tupledealloc (tupleobject.c:183)
==16458==    by 0x8131C8B: code_dealloc (codeobject.c:261)
==16458==    by 0x80A5F43: tupledealloc (tupleobject.c:170)
==16458==    by 0x8131C8B: code_dealloc (codeobject.c:261)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC8A3: import_module_level (import.c:2140)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==  Address 0x44b2010 is 37,760 bytes inside a block of size 38,420 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x8100507: PyMarshal_ReadLastObjectFromFile (marshal.c:1068)
==16458==    by 0x80FB3B1: load_source_module (import.c:769)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC8A3: import_module_level (import.c:2140)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x80946D8: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC8A3: import_module_level (import.c:2140)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x80946E9: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC8A3: import_module_level (import.c:2140)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80D8B2C: T.463 (ceval.c:3931)
==16458==    by 0x80DB7AB: PyEval_EvalFrame_value (ceval.c:2357)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x80946D8: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FBA88: load_package (import.c:1073)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC8A3: import_module_level (import.c:2140)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x80946E9: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8131BC2: code_dealloc (codeobject.c:270)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FBA88: load_package (import.c:1073)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC8A3: import_module_level (import.c:2140)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x80DA061: PyEval_EvalFrame_value (ceval.c:1202)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==  Address 0x456d010 is 5 bytes after a block of size 267 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072F38: get_line (fileobject.c:1392)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x809EF9F: string_repr (stringobject.c:923)
==16458==    by 0x8092B24: PyObject_Repr (object.c:376)
==16458==    by 0x807D390: PyInt_FromString (intobject.c:373)
==16458==    by 0x8061CD6: int_from_string (abstract.c:1446)
==16458==    by 0x80628DB: PyNumber_Int (abstract.c:1634)
==16458==    by 0x807D0FF: int_new (intobject.c:978)
==16458==    by 0x80AA05C: type_call (typeobject.c:727)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80DC4FC: PyEval_EvalFrame_value (ceval.c:4299)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x456d010 is 5 bytes after a block of size 267 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072F38: get_line (fileobject.c:1392)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x80A0B36: PyString_FromFormatV (stringobject.c:342)
==16458==    by 0x80F46DC: PyErr_Format (errors.c:546)
==16458==    by 0x807D3C1: PyInt_FromString (intobject.c:377)
==16458==    by 0x8061CD6: int_from_string (abstract.c:1446)
==16458==    by 0x80628DB: PyNumber_Int (abstract.c:1634)
==16458==    by 0x807D0FF: int_new (intobject.c:978)
==16458==    by 0x80AA05C: type_call (typeobject.c:727)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80DC4FC: PyEval_EvalFrame_value (ceval.c:4299)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x456d010 is 5 bytes after a block of size 267 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072F38: get_line (fileobject.c:1392)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x807D3D9: PyInt_FromString (intobject.c:380)
==16458==    by 0x8061CD6: int_from_string (abstract.c:1446)
==16458==    by 0x80628DB: PyNumber_Int (abstract.c:1634)
==16458==    by 0x807D0FF: int_new (intobject.c:978)
==16458==    by 0x80AA05C: type_call (typeobject.c:727)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80DC4FC: PyEval_EvalFrame_value (ceval.c:4299)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==  Address 0x456d010 is 5 bytes after a block of size 267 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072F38: get_line (fileobject.c:1392)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x811C3B3: match_dealloc (_sre.c:3209)
==16458==    by 0x80DA061: PyEval_EvalFrame_value (ceval.c:1202)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x456d010 is 5 bytes after a block of size 267 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072F38: get_line (fileobject.c:1392)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x806F50F: BaseException_dealloc (exceptions.c:79)
==16458==    by 0x808CE68: insertdict (dictobject.c:459)
==16458==    by 0x808F2C6: PyDict_SetItem (dictobject.c:701)
==16458==    by 0x808F482: PyDict_SetItemString (dictobject.c:2301)
==16458==    by 0x810B0A1: PySys_SetObject (sysmodule.c:83)
==16458==    by 0x80DC41B: PyEval_EvalFrame_value (ceval.c:3431)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x456d010 is 5 bytes after a block of size 267 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072F38: get_line (fileobject.c:1392)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8137FE9: frame_dealloc (frameobject.c:444)
==16458==    by 0x80D9CCD: PyEval_EvalFrame_value (ceval.c:2978)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x45ad010 is 176 bytes inside a block of size 1,278 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x80DA061: PyEval_EvalFrame_value (ceval.c:1202)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072E48: get_line (fileobject.c:1384)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x45c7010 is 216 bytes inside a block of size 327 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x80DA061: PyEval_EvalFrame_value (ceval.c:1202)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072F38: get_line (fileobject.c:1392)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x45c8010 is 200 bytes inside a block of size 267 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x8072E48: get_line (fileobject.c:1384)
==16458==    by 0x80750F4: file_readline (fileobject.c:1515)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x8094BA9: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x80D87CC: string_concatenate (ceval.c:4903)
==16458==    by 0x80DD6BF: PyEval_EvalFrame_value (ceval.c:1402)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==  Address 0x46ce010 is 784 bytes inside a block of size 1,064 free'd
==16458==    at 0x4024836: free (vg_replace_malloc.c:325)
==16458==    by 0x811CAF8: state_fini (_sre.c:260)
==16458==    by 0x8122001: pattern_search (_sre.c:1934)
==16458==    by 0x80DEA64: PyEval_EvalFrame_value (ceval.c:4067)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x806F50F: BaseException_dealloc (exceptions.c:79)
==16458==    by 0x808E770: PyDict_DelItem (dictobject.c:755)
==16458==    by 0x808E7DB: PyDict_DelItemString (dictobject.c:2314)
==16458==    by 0x80D9B45: PyEval_EvalFrame_value (ceval.c:3465)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==  Address 0x470a010 is 480 bytes inside a block of size 826 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x809EF9F: string_repr (stringobject.c:923)
==16458==    by 0x8092B24: PyObject_Repr (object.c:376)
==16458==    by 0x807D390: PyInt_FromString (intobject.c:373)
==16458==    by 0x8061CD6: int_from_string (abstract.c:1446)
==16458==    by 0x80628DB: PyNumber_Int (abstract.c:1634)
==16458==    by 0x807D0FF: int_new (intobject.c:978)
==16458==    by 0x80AA05C: type_call (typeobject.c:727)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==    by 0x80DC4FC: PyEval_EvalFrame_value (ceval.c:4299)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x811C3B3: match_dealloc (_sre.c:3209)
==16458==    by 0x8137FE9: frame_dealloc (frameobject.c:444)
==16458==    by 0x80D9CCD: PyEval_EvalFrame_value (ceval.c:2978)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==  Address 0x4709010 is 200 bytes inside a block of size 354 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x809E0ED: _PyString_Resize (stringobject.c:4277)
==16458==    by 0x80D87CC: string_concatenate (ceval.c:4903)
==16458==    by 0x80DD6BF: PyEval_EvalFrame_value (ceval.c:1402)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x8094BB2: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x8111938: _PyObject_GC_Resize (gcmodule.c:1404)
==16458==    by 0x81387F1: PyFrame_New (frameobject.c:679)
==16458==    by 0x80DDCD5: PyEval_EvalFrame_value (ceval.c:4143)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x8094BBD: PyObject_Realloc (obmalloc.c:1154)
==16458==    by 0x8111938: _PyObject_GC_Resize (gcmodule.c:1404)
==16458==    by 0x81387F1: PyFrame_New (frameobject.c:679)
==16458==    by 0x80DDCD5: PyEval_EvalFrame_value (ceval.c:4143)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458== 
==16458== Invalid read of size 4
==16458==    at 0x80946CF: PyObject_Free (obmalloc.c:931)
==16458==    by 0x80A5F59: tupledealloc (tupleobject.c:183)
==16458==    by 0x8131C73: code_dealloc (codeobject.c:262)
==16458==    by 0x80A5F43: tupledealloc (tupleobject.c:170)
==16458==    by 0x8131C8B: code_dealloc (codeobject.c:261)
==16458==    by 0x80FB2D3: load_source_module (import.c:1018)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC8A3: import_module_level (import.c:2140)
==16458==    by 0x80FCEE6: PyImport_ImportModuleLevel (import.c:2184)
==16458==    by 0x80D74AE: builtin___import__ (bltinmodule.c:50)
==16458==    by 0x8061193: PyObject_Call (abstract.c:2502)
==16458==  Address 0x493c010 is 504 bytes inside a block of size 804 free'd
==16458==    at 0x4024D12: realloc (vg_replace_malloc.c:476)
==16458==    by 0x8081E6C: PyList_Append (listobject.c:62)
==16458==    by 0x80FE916: r_object (marshal.c:731)
==16458==    by 0x80FE0DB: r_object (marshal.c:794)
==16458==    by 0x80FE56A: r_object (marshal.c:930)
==16458==    by 0x80FE0DB: r_object (marshal.c:794)
==16458==    by 0x80FE559: r_object (marshal.c:927)
==16458==    by 0x81004D1: PyMarshal_ReadLastObjectFromFile (marshal.c:1107)
==16458==    by 0x80FB3B1: load_source_module (import.c:769)
==16458==    by 0x80FC092: import_submodule (import.c:2591)
==16458==    by 0x80FC364: load_next (import.c:2411)
==16458==    by 0x80FC8A3: import_module_level (import.c:2140)
==16458== 
==16458== Conditional jump or move depends on uninitialised value(s)
==16458==    at 0x80946D8: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8137FE9: frame_dealloc (frameobject.c:444)
==16458==    by 0x80D9CCD: PyEval_EvalFrame_value (ceval.c:2978)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Use of uninitialised value of size 4
==16458==    at 0x80946E9: PyObject_Free (obmalloc.c:931)
==16458==    by 0x8137FE9: frame_dealloc (frameobject.c:444)
==16458==    by 0x80D9CCD: PyEval_EvalFrame_value (ceval.c:2978)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458==    by 0x80DC65D: PyEval_EvalFrame_value (ceval.c:2999)
==16458==    by 0x80DEC9D: PyEval_EvalFrameEx_slp (ceval.c:836)
==16458== 
==16458== Invalid write of size 4
==16458==    at 0x80DF749: slp_kill_tasks_with_stacks (stacklesseval.c:349)
==16458==    by 0x81055A1: Py_Finalize (pythonrun.c:416)
==16458==    by 0x8104FCE: handle_system_exit (pythonrun.c:1785)
==16458==    by 0x80E22D3: slp_run_tasklet (scheduling.c:1087)
==16458==    by 0x80DFD1B: slp_eval_frame (stacklesseval.c:299)
==16458==    by 0x80DFD6C: climb_stack_and_eval_frame (stacklesseval.c:266)
==16458==    by 0x80DFCC3: slp_eval_frame (stacklesseval.c:294)
==16458==    by 0x80D84F6: PyEval_EvalCode (ceval.c:543)
==16458==    by 0x8105D6B: PyRun_FileExFlags (pythonrun.c:1379)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
==16458== 
==16458== 
==16458== Process terminating with default action of signal 11 (SIGSEGV)
==16458==  Access not within mapped region at address 0x8
==16458==    at 0x80DF749: slp_kill_tasks_with_stacks (stacklesseval.c:349)
==16458==    by 0x81055A1: Py_Finalize (pythonrun.c:416)
==16458==    by 0x8104FCE: handle_system_exit (pythonrun.c:1785)
==16458==    by 0x80E22D3: slp_run_tasklet (scheduling.c:1087)
==16458==    by 0x80DFD1B: slp_eval_frame (stacklesseval.c:299)
==16458==    by 0x80DFD6C: climb_stack_and_eval_frame (stacklesseval.c:266)
==16458==    by 0x80DFCC3: slp_eval_frame (stacklesseval.c:294)
==16458==    by 0x80D84F6: PyEval_EvalCode (ceval.c:543)
==16458==    by 0x8105D6B: PyRun_FileExFlags (pythonrun.c:1379)
==16458==    by 0x8105F31: PyRun_SimpleFileExFlags (pythonrun.c:952)
==16458==    by 0x805C7FA: Py_Main (main.c:572)
==16458==    by 0x805BAAA: main (python.c:23)
==16458==  If you believe this happened as a result of a stack
==16458==  overflow in your program's main thread (unlikely but
==16458==  possible), you can try to increase the size of the
==16458==  main thread stack using the --main-stacksize= flag.
==16458==  The main thread stack size used in this run was 8388608.
==16458== 
==16458== HEAP SUMMARY:
==16458==     in use at exit: 1,857,378 bytes in 1,206 blocks
==16458==   total heap usage: 9,106 allocs, 7,900 frees, 7,212,718 bytes allocated
==16458== 
==16458== LEAK SUMMARY:
==16458==    definitely lost: 0 bytes in 0 blocks
==16458==    indirectly lost: 0 bytes in 0 blocks
==16458==      possibly lost: 105,721 bytes in 252 blocks
==16458==    still reachable: 1,751,657 bytes in 954 blocks
==16458==         suppressed: 0 bytes in 0 blocks
==16458== Rerun with --leak-check=full to see details of leaked memory
==16458== 
==16458== For counts of detected and suppressed errors, rerun with: -v
==16458== Use --track-origins=yes to see where uninitialised values come from
==16458== ERROR SUMMARY: 1362 errors from 56 contexts (suppressed: 31 from 13)
